### ISSUE TITLE
wf.Contains has a bug

### ISSUE THREAD

**Issue by pikapiyyy** [syyongx/go-wordsfilter#1]
texts := []string{
        "Miyamoto Musashi",
        "妲己",
        "アンジェラ",
        "ความรุ่งโรจน์",
}
wf := wordsfilter.New()

// Generate
root := wf.Generate(texts)

c1 := wf.Contains("妲己", root)
// c1 true
c2 := wf.Contains("妲己2333", root)
// c2 false

Why c2 is false?

**Comment by syyongx** [comment]
74232c7 has fixed it. 

Thank you very much for the problem you found.
